steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/ts-test-node/nice-rollup", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ts-test-node/nice-rollup"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "nice-rollup",
        "--image",
        "gcr.io/ts-test-node/nice-rollup",
        "--region",
        "europe-west3",
        "--platform",
        "managed",

        "--allow-unauthenticated",

        "--set-env-vars",
        "NODE_ENV=production"
      ]
images:
  - gcr.io/ts-test-node/nice-rollup
